name: flutter_application_demo1
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cache_manager: ^1.0.0+3
  concentric_transition: ^1.0.1+1
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.9
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.7.0
  http: ^1.2.0
  lottie: ^3.0.0
  provider: ^6.0.1
  razorpay_flutter: ^1.2.7
  salomon_bottom_bar: ^3.1.0
  shared_preferences: ^2.0.8
  shimmer: ^3.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#42a5f5"
  image: assets/splash.png
  android: true
  ios: true
  web: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/shoes/
    - assets/images/misc/
    - assets/images/logo/

  fonts:
    - family: Contax
      fonts:
        - asset: assets/fonts/contax.ttf
